const hotels = [
    {
        id: 0,
        name: "Fortune Jp Palace",
        imgLink: require('../img/hotels/fjp.jpeg'),
        rating: 5,
        distance_from_City_centre: "3.6 km" ,
        Tariff: "Rs 2,472",
        Free_cancellation: true,
        Description: "Boasting a palatial-style architecture, Fortune Jp Palace is positioned in central Mysore and features views of the famous Chamundi Hills. The polished hotel takes pride in its landscaped gardens, courtyard swimming pool, and modern fitness centre.",
    },
    {
        id: 1,
        name: "The Windflower Resorts & Spa Mysore",
        imgLink: require('../img/hotels/wfr.jpeg'),
        rating: 4,
        distance_from_City_centre:"3.4 km" ,
        Tariff: "Rs 5,315",
        Free_cancellation: true,
        Description: "Situated near the Chamundi foothills in Mysore, The Windflower Resorts & Spa Mysore offers indoor and outdoor games as well as a kids' play area. Modern studios, suites, and villas are all available. All are en suite with some featuring an open-air rain shower, as well as a private patio area.",
    },
    {
        id: 2,
        name: "Grand Mercure Mysuru",
        imgLink: require('../img/hotels/gm.jpeg'),
        rating: 5,
        distance_from_City_centre:"3.9 km" ,
        Tariff: "Rs 2,895",
        Free_cancellation: true,
        Description: "Grand Mercure Mysuru is a luxury hotel in the centre of Mysore that's suitable for both business and leisure travellers. It's located on the popular Dasara Pathway Procession and features a rooftop pool and spa. All rooms and suites are air-conditioned and have en-suite bathrooms.",
    },
    {
        id: 3,
        name: "Treebo Trend Akshaya Mahal Inn",
        imgLink: require('../img/hotels/tta.jpeg'),
        rating: 3,
        distance_from_City_centre: "3.6 km",
        Tariff: "Rs 1,535",
        Free_cancellation: false,
        Description: "Located in the heritage city of Mysore is Treebo Akshaya Mahal Inn, a 3-star property that is perfect for business travellers, couples, families and groups. This 3-floor building is located on Abba Road and is located close to sites like St. Philomena’s Cathedral, Mysore Zoo, Mysore Palace, and Mini Vidhan Soudha.",
    },
    {
        id: 4,
        name: "Mannars Residency",
        imgLink: require('../img/hotels/mannars.jpeg'),
        rating: 1,
        distance_from_City_centre: "2.0 km",
        Tariff: "Rs 1,236",
        Free_cancellation: true,
        Description: "Mannars Residency is a local chain property offering budget accommodation at multi-storey premises in the inner suburbs of the city. Mysore Junction railway station is conveniently situated less than ten minutes’ stroll away.",
    },
    {
        id: 5,
        name: "Hotel Sunflower",
        imgLink: require('../img/hotels/sf.jpeg'),
        rating: 2,
        distance_from_City_centre: "4.9 km",
        Tariff: "Rs 1,438",
        Free_cancellation: true,
        Description: "Located just five kilometres from the Mysore Railway Station, Hotel Sunflower offers meeting facilities and free Wi-Fi in a luxurious environment. Rooms at Hotel Sunflower have amenities such as satellite TV, coffee/tea machines, and private bathrooms stocked with free toiletries and hairdryers.",
    },
]

export default hotels;
